[package]
name = "identity_pqc_verifier"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "identity", "jose", "jwk", "jws"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "JWS PQC signature verification for IOTA Identity"

[dependencies]
identity_jose = { version = "=1.1.0-alpha.1", path = "../identity_jose", default-features = false }
oqs = {version = "0.9.0", default-features = false, features = ["sigs", "std", "vendored"] }

[features]
ml_dsa_44 = []
ml_dsa_65 = []
ml_dsa_87 = []
default = ["ml_dsa_44", "ml_dsa_65", "ml_dsa_87"]